### ISSUE TITLE
when running the example, an error occurs

### ISSUE THREAD

**Issue by reinierdevl** [stevemarple/python-MCP342x#6]
when running on a pi3b ith latest (today) Rasbian and Thonny python IDE (3.7.3), I get a error result when I start the example

%Run mpc3432.py
Traceback (most recent call last):
  File "/home/pi/AirQuality/MCP3424 ADC/mpc3432.py", line 55, in <module>
    r = MCP342x.convert_and_read_many(adcs, samples=2)
  File "/home/pi/.local/lib/python3.7/site-packages/MCP342x/__init__.py", line 145, in convert_and_read_many
    a.configure()
  File "/home/pi/.local/lib/python3.7/site-packages/MCP342x/__init__.py", line 293, in configure
    + ' gain: ' + str(self.get_gain()))
  File "/home/pi/.local/lib/python3.7/site-packages/MCP342x/__init__.py", line 221, in get_channel
    return [g for g, c in MCP342x._channel_to_config.iteritems() if c == self.config & MCP342x._channel_mask][0]
AttributeError: 'dict' object has no attribute 'iteritems'

**Comment by Grandpa-G** [comment]
This works

`To get rid of this Error: “ 'dict' object has no attribute 'iteritems' ” if you are using python3, you can use the dict.items()function instead of dict.iteritems().

The dict.iteritems() is removed in python3, so this function can't be used anymore.

But if you are a user of Python 2 then you can use  dict.iteritems() to get rid of this err`
